# Generated by Django 5.0.1 on 2024-01-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
