"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv, find_dotenv
import os

#finding and laoding project environemnt paths
env_path = find_dotenv()
load_dotenv(env_path)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    "corsheaders",          #intalled
    "rest_framework",
    
    "authentication",       #apps
    "registration",
    "user"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

SECURITY_ENGINE = [
    {
        'AURS_5Pck_Eng_v9':{
            'Channel_pack_plugin':";LKKJ8U&&YUD__F#CONIO.h",
        },
        "Channel_port":1220,
        "Socket_Insertion":{
            "DEBO_2":{},
            "DEBO_3":{},
            "FEV_ALPH":{
                "BETA_COUNTER":12221,
                "LINK_SOCKET":"DEBO_@2",
                "PRE_INSERTION":{
                    "SERVLET":{
                        "HOST":"http://ferversocket.io/",
                        "PORT":1221,
                        "DATABASE":"N/A",
                        "USER":"ADMIN",
                        "FIREWALL_SWITCH":{
                            "MIDDLEWARE_SWITCH":{ 'django.middleware.security.SecurityMiddleware'},
                            "GATEWAY_COUNTER":{
                                "CMD":"host --pass login:ADMIN/password@123/",
                                "FALSIFY":True
                            }
                        }
                    },
                    "CMD":"host --link load=prefix:/DEBO@2/ --IN /HEV@DELT/  --OUT /FEV:GAM/ insert[socket=rand.oulet()]"
                }
            },
            "FEV_DELT":{
                "ALPHA_COUNTER":12221,
                "OBS":None,
                "CONFIG":{
                    "SECRET_KEY_ENGINE":{},
                    "X-CROSS:AC2":{
                        "GATEWAY":{
                            
                        },
                        "ISL":{
                            
                        },
                        "ROUTER":{
                            
                        }
                    },"X-CROSS:FW7":{
                        
                    }
                },
                "PACKET_RECEIVE":"/FEV_ALPHA/",
                "PACKET_THROUGH":"/FEV_NULLABLE/",
                "PACKET_SEND":"/FEV_GAM/",
            },
            "FEV:GAM":{},
        }
    },
]


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DATABASE_NAME"),
        'USER':os.getenv("DATABASE_USER"),
        'PASSWORD':os.getenv("DATABASE_PASSWORD"),
        'HOST':os.getenv("DATABASE_HOST"),
        'PORT':os.getenv("DATABASE_PORT")
    }
}

AUTHENTICATION_BACKENDS = [
    "authentication.base_auth.AuthBackend"
]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
